#!/bin/bash

currentDir=$(pwd)
genNewKey=false

echo "Do you wish to install generate a new key pair?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) genNewKey=true; break;;
        No ) break;;
    esac
done

sudo mkdir -p /var/vbox-key
cd /var/vbox-key

if [ $genNewKey = true ]; then
    sudo openssl req -new -x509 -newkey rsa:2048 -keyout vboxdrv.priv -outform DER -out vboxdrv.der -nodes -days 36500 -subj "/CN=MySelf/"
fi

sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./vboxdrv.priv ./vboxdrv.der $(modinfo -n vboxdrv)
sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./vboxdrv.priv ./vboxdrv.der $(modinfo -n vboxnetflt)
sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./vboxdrv.priv ./vboxdrv.der $(modinfo -n vboxnetadp)
sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./vboxdrv.priv ./vboxdrv.der $(modinfo -n vboxpci)
echo "Enter password for MOK"
sudo mokutil --import vboxdrv.der

echo "Please reboot"